2022-05-16 19:47:10,599 ERROR: Exception on /user/test_user [GET] [in /home/max/Python/microblog/venv/lib/python3.10/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/max/Python/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/max/Python/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/max/Python/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/max/Python/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/max/Python/microblog/venv/lib/python3.10/site-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/max/Python/microblog/app/routes.py", line 72, in user
    return render_template("user.html", user=user, posts=posts, form=form)
  File "/home/max/Python/microblog/venv/lib/python3.10/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/home/max/Python/microblog/venv/lib/python3.10/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/max/Python/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/max/Python/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/max/Python/microblog/app/templates/user.html", line 1, in top-level template code
    {% block content %}
  File "/home/max/Python/microblog/app/templates/user.html", line 48, in block 'content'
    {% include 'post.html' %}
  File "/home/max/Python/microblog/venv/lib/python3.10/site-packages/flask/templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "/home/max/Python/microblog/venv/lib/python3.10/site-packages/flask/templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _post.html
2022-05-16 19:47:15,147 ERROR: Exception on /user/test_user [GET] [in /home/max/Python/microblog/venv/lib/python3.10/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/max/Python/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/max/Python/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/max/Python/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/max/Python/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/max/Python/microblog/venv/lib/python3.10/site-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/max/Python/microblog/app/routes.py", line 72, in user
    return render_template("user.html", user=user, posts=posts, form=form)
  File "/home/max/Python/microblog/venv/lib/python3.10/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/home/max/Python/microblog/venv/lib/python3.10/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/max/Python/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/max/Python/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/max/Python/microblog/app/templates/user.html", line 1, in top-level template code
    {% block content %}
  File "/home/max/Python/microblog/app/templates/user.html", line 48, in block 'content'
    {% include 'post.html' %}
  File "/home/max/Python/microblog/venv/lib/python3.10/site-packages/flask/templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "/home/max/Python/microblog/venv/lib/python3.10/site-packages/flask/templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _post.html
2022-05-16 19:48:37,372 ERROR: Exception on /user/test_user [GET] [in /home/max/Python/microblog/venv/lib/python3.10/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/max/Python/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/max/Python/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/max/Python/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/max/Python/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/max/Python/microblog/venv/lib/python3.10/site-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/max/Python/microblog/app/routes.py", line 72, in user
    return render_template("user.html", user=user, posts=posts, form=form)
  File "/home/max/Python/microblog/venv/lib/python3.10/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/home/max/Python/microblog/venv/lib/python3.10/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/max/Python/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/max/Python/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/max/Python/microblog/app/templates/user.html", line 1, in top-level template code
    {% block content %}
  File "/home/max/Python/microblog/app/templates/user.html", line 48, in block 'content'
  File "/home/max/Python/microblog/venv/lib/python3.10/site-packages/flask/templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "/home/max/Python/microblog/venv/lib/python3.10/site-packages/flask/templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _post.html
2022-05-16 19:48:40,348 INFO: Microblog startup [in /home/max/Python/microblog/app/__init__.py:44]
2022-05-17 09:46:48,079 INFO: Microblog startup [in /home/max/Python/microblog/app/__init__.py:44]
2022-05-17 10:14:13,318 INFO: Microblog startup [in /home/max/Python/microblog/app/__init__.py:44]
